# Site settings
title: Diary of a Developer
#email: szunyog@gmail.com
description: "Diary of a Developer is about .NET, SQL, Python or other interesting topics."
baseurl: ""
url: "http://szunyog.github.io"
#twitter_username: jekyllrb
github_username: szunyog

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
