# Site settings
title: Diary of a Developer
#email: szunyog@gmail.com
description: ""
baseurl: ""
url: "http://szunyog.github.io"
#twitter_username: jekyllrb
github_username: szunyog

# Build settings
markdown: kramdown
permalink: pretty
